AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "Gemfile"
    - "Rakefile"
    - "gems.gemspec"

# Avoid long parameter lists
ParameterLists:
  Max: 4
  CountKeywordArgs: true

MethodLength:
  CountComments: false
  Max: 10

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 2

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    map: "collect"
    reduce: "inject"
    find: "detect"
    find_all: "select"

# Limit line length
LineLength:
  Enabled: false

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Enforce Ruby 1.8-compatible hash syntax
HashSyntax:
  EnforcedStyle: hash_rockets

# No spaces inside hash literals
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Allow dots at the end of lines
DotPosition:
  Enabled: false

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

# Enforce outdenting of access modifiers (i.e. public, private, protected)
AccessModifierIndentation:
  EnforcedStyle: outdent

EmptyLinesAroundAccessModifier:
  Enabled: true

# Align ends correctly
EndAlignment:
  EnforcedStyleAlignWith: variable

# Indentation of when/else
CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false

Lambda:
  Enabled: false

RaiseArgs:
  EnforcedStyle: compact

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Ignore length of describe and context blocks
Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

# The RubyGems /api/v1/dependencies endpoint returns serialized ruby objects
# that need to be deserialized within Gems::Client#dependencies. :(
Security/MarshalLoad:
  Enabled: false
