plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - standard-custom
  - standard-performance

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable

# Standard disables the Metrics cops; enforce them at RuboCop's defaults
Metrics/AbcSize:
  Enabled: true

Metrics/BlockLength:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Metrics/ClassLength:
  Enabled: true

Metrics/CollectionLiteralLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/MethodLength:
  Enabled: true

Metrics/ModuleLength:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: true
