module Gems
  VERSION: String

  class Version
    MAJOR: Integer
    MINOR: Integer
    PATCH: Integer
    PRE: String?

    def self.to_s: () -> String
  end

  type multipart_field = [Symbol | String, untyped] | [String, String, Hash[Symbol, String]]
  type options = Hash[Symbol, untyped]
  type request_body = Hash[Symbol | String, untyped] | Array[multipart_field] | String

  extend Configuration
  extend SingleForwardable

  def self.new: (?host: String, ?key: String?, ?username: String?, ?password: String?, ?otp: String?, ?id_token: String?, ?user_agent: String, ?open_timeout: Integer, ?read_timeout: Integer, ?write_timeout: Integer, ?debug_output: IO?, ?proxy_url: String?, ?max_redirects: Integer) -> Client
  def self.info: (String gem_name) -> untyped
  def self.version: (String gem_name, String version) -> untyped
  def self.search: (String query, ?options options) -> untyped
  def self.gems: (?String? user_handle) -> untyped
  def self.push: (File gem, ?String? host, ?attestations: Array[File]?) -> String
  def self.yank: (String gem_name, ?String? gem_version, ?options options) -> String
  def self.unyank: (String gem_name, ?String? gem_version, ?options options) -> String
  def self.versions: (String gem_name) -> untyped
  def self.latest_version: (String gem_name) -> untyped
  def self.total_downloads: (?String? gem_name, ?String? gem_version) -> untyped
  def self.most_downloaded: () -> untyped
  def self.owners: (String gem_name) -> untyped
  def self.add_owner: (String gem_name, String owner) -> String
  def self.remove_owner: (String gem_name, String owner) -> String
  def self.web_hooks: () -> untyped
  def self.add_web_hook: (String gem_name, String url) -> String
  def self.remove_web_hook: (String gem_name, String url) -> String
  def self.fire_web_hook: (String gem_name, String url) -> String
  def self.latest: (?options options) -> untyped
  def self.just_updated: (?options options) -> untyped
  def self.api_key: () -> String
  def self.create_api_key: (String name, ?options options) -> String
  def self.update_api_key: (String key, ?options options) -> String
  def self.exchange_trusted_publisher_token: (String id_token) -> untyped
  def self.reverse_dependencies: (String gem_name, ?options options) -> untyped

  module Configuration
    DEFAULT_HOST: String
    DEFAULT_USER_AGENT: String

    attr_accessor host: String
    attr_accessor id_token: String?
    attr_writer key: String?
    attr_accessor otp: String?
    attr_accessor password: String?
    attr_accessor user_agent: String
    attr_accessor username: String?
    attr_accessor open_timeout: Integer
    attr_accessor read_timeout: Integer
    attr_accessor write_timeout: Integer
    attr_accessor debug_output: IO?
    attr_accessor proxy_url: String?
    attr_accessor max_redirects: Integer

    def self.extended: (Configuration base) -> void
    def key: () -> String?
    def default_key: () -> String?
    def configure: () { (self) -> void } -> self
    def reset: () -> self

    private

    def reset_credentials: () -> void
    def reset_connection: () -> void
  end

  class Authenticator
    AUTHENTICATION_HEADER: String

    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
  end

  class ApiKeyAuthenticator < Authenticator
    attr_accessor key: String

    def initialize: (key: String) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
  end

  class BasicAuthenticator < Authenticator
    attr_accessor username: String
    attr_accessor password: String

    def initialize: (username: String, password: String) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
  end

  class OtpAuthenticator < Authenticator
    OTP_HEADER: String

    attr_accessor authenticator: Authenticator
    attr_accessor otp: String

    def initialize: (authenticator: Authenticator, otp: String) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
  end

  class TrustedPublisherAuthenticator < Authenticator
    EXCHANGE_TOKEN_PATH: String
    JSON_CONTENT_TYPE: String

    attr_accessor id_token: String
    attr_accessor host: String
    attr_accessor connection: Connection
    attr_accessor request_builder: RequestBuilder
    attr_reader api_key: String?

    def initialize: (id_token: String, ?host: String, ?connection: Connection, ?request_builder: RequestBuilder) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
    def exchange_token!: () -> untyped
  end

  module ClientCredentials
    @host: String
    @connection: Connection
    @request_builder: RequestBuilder

    attr_reader key: String?
    attr_reader username: String?
    attr_reader password: String?
    attr_reader otp: String?
    attr_reader id_token: String?
    attr_reader authenticator: Authenticator

    def key=: (String? key) -> void
    def username=: (String? username) -> void
    def password=: (String? password) -> void
    def otp=: (String? otp) -> void
    def id_token=: (String? id_token) -> void

    private

    def initialize_credentials: (key: String?, username: String?, password: String?, otp: String?, id_token: String?) -> void
    def initialize_authenticator: () -> Authenticator
    def otp_authenticator: (Authenticator authenticator) -> Authenticator
    def basic_authenticator: () -> BasicAuthenticator?
    def trusted_publisher_authenticator: () -> TrustedPublisherAuthenticator?
    def api_key_authenticator: () -> ApiKeyAuthenticator?
  end

  interface _Requests
    def host: () -> String
    def connection: () -> Connection
    def request_builder: () -> RequestBuilder
    def get: (String path, ?Hash[Symbol | String, untyped] params, ?host: String?) -> String
    def delete: (String path, ?Hash[Symbol | String, untyped] params, ?host: String?) -> String
    def post: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String
    def put: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String
    def patch: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String
  end

  module API : Object, _Requests
    def info: (String gem_name) -> untyped
    def version: (String gem_name, String version) -> untyped
    def search: (String query, ?options options) -> untyped
    def gems: (?String? user_handle) -> untyped
    def push: (File gem, ?String? host, ?attestations: Array[File]?) -> String
    def yank: (String gem_name, ?String? gem_version, ?options options) -> String
    def unyank: (String gem_name, ?String? gem_version, ?options options) -> String
    def versions: (String gem_name) -> untyped
    def latest_version: (String gem_name) -> untyped
    def total_downloads: (?String? gem_name, ?String? gem_version) -> untyped
    def most_downloaded: () -> untyped
    def owners: (String gem_name) -> untyped
    def add_owner: (String gem_name, String owner) -> String
    def remove_owner: (String gem_name, String owner) -> String
    def web_hooks: () -> untyped
    def add_web_hook: (String gem_name, String url) -> String
    def remove_web_hook: (String gem_name, String url) -> String
    def fire_web_hook: (String gem_name, String url) -> String
    def latest: (?options options) -> untyped
    def just_updated: (?options options) -> untyped
    def api_key: () -> String
    def create_api_key: (String name, ?options options) -> String
    def update_api_key: (String key, ?options options) -> String
    def exchange_trusted_publisher_token: (String id_token) -> untyped
    def reverse_dependencies: (String gem_name, ?options options) -> untyped

  end

  class Client
    include API
    extend Forwardable
    include ClientCredentials

    @connection: Connection
    @request_builder: RequestBuilder
    @redirect_handler: RedirectHandler
    @response_parser: ResponseParser

    attr_reader host: String
    attr_reader connection: Connection
    attr_reader request_builder: RequestBuilder

    def host=: (String host) -> void
    def inspect: () -> String
    def open_timeout: () -> Integer
    def read_timeout: () -> Integer
    def write_timeout: () -> Integer
    def proxy_url: () -> String?
    def debug_output: () -> IO?
    def open_timeout=: (Integer open_timeout) -> void
    def read_timeout=: (Integer read_timeout) -> void
    def write_timeout=: (Integer write_timeout) -> void
    def proxy_url=: (String proxy_url) -> void
    def debug_output=: (IO? debug_output) -> void
    def max_redirects: () -> Integer
    def max_redirects=: (Integer max_redirects) -> void
    def user_agent: () -> String
    def user_agent=: (String user_agent) -> void

    def initialize: (?host: String, ?key: String?, ?username: String?, ?password: String?, ?otp: String?, ?id_token: String?, ?user_agent: String, ?open_timeout: Integer, ?read_timeout: Integer, ?write_timeout: Integer, ?debug_output: IO?, ?proxy_url: String?, ?max_redirects: Integer) -> void
    def get: (String path, ?Hash[Symbol | String, untyped] params, ?host: String?) -> String
    def delete: (String path, ?Hash[Symbol | String, untyped] params, ?host: String?) -> String
    def post: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String
    def put: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String
    def patch: (String path, ?request_body body, ?content_type: String?, ?host: String?) -> String

    private

    def execute_request: (Symbol http_method, String path, host: String?, ?params: Hash[Symbol | String, untyped], ?body: request_body?, ?content_type: String?) -> String
  end

  class Error < StandardError
  end

  class HTTPError < Error
    attr_reader response: Net::HTTPResponse
    attr_reader code: String

    def initialize: (response: Net::HTTPResponse) -> void

    private

    def error_message: (Net::HTTPResponse response) -> String
  end

  class ClientError < HTTPError
  end

  class ServerError < HTTPError
  end

  class BadRequest < ClientError
  end

  class Unauthorized < ClientError
  end

  class Forbidden < ClientError
  end

  class NotFound < ClientError
  end

  class Conflict < ClientError
  end

  class UnprocessableEntity < ClientError
  end

  class TooManyRequests < ClientError
  end

  class InternalServerError < ServerError
  end

  class BadGateway < ServerError
  end

  class ServiceUnavailable < ServerError
  end

  class GatewayTimeout < ServerError
  end

  class NetworkError < Error
  end

  class TooManyRedirects < Error
  end

  class Connection
    extend Forwardable

    DEFAULT_OPEN_TIMEOUT: Integer
    DEFAULT_READ_TIMEOUT: Integer
    DEFAULT_WRITE_TIMEOUT: Integer
    NETWORK_ERRORS: Array[singleton(EOFError) | singleton(Errno::ECONNREFUSED) | singleton(Errno::ECONNRESET) | singleton(Errno::EHOSTUNREACH) | singleton(Errno::ETIMEDOUT) | singleton(Net::OpenTimeout) | singleton(Net::ReadTimeout) | singleton(Net::WriteTimeout) | singleton(OpenSSL::SSL::SSLError) | singleton(SocketError)]

    attr_accessor open_timeout: Integer
    attr_accessor read_timeout: Integer
    attr_accessor write_timeout: Integer
    attr_accessor debug_output: IO?
    attr_reader proxy_url: String?
    attr_reader proxy_uri: URI::Generic?

    def proxy_host: () -> String?
    def proxy_port: () -> Integer?
    def proxy_user: () -> String?
    def proxy_pass: () -> String?

    def initialize: (?open_timeout: Integer, ?read_timeout: Integer, ?write_timeout: Integer, ?debug_output: IO?, ?proxy_url: String?) -> void
    def perform: (request: Net::HTTPRequest) -> Net::HTTPResponse
    def proxy_url=: (String proxy_url) -> void

    private

    def build_http_client: (URI::Generic uri) -> Net::HTTP
    def configure_http_client: (Net::HTTP http_client) -> Net::HTTP
  end

  class RequestBuilder
    FORM_URLENCODED: String
    MULTIPART_FORM_DATA: String
    OCTET_STREAM: String
    HTTP_METHODS: Hash[Symbol, singleton(Net::HTTP::Get) | singleton(Net::HTTP::Post) | singleton(Net::HTTP::Put) | singleton(Net::HTTP::Patch) | singleton(Net::HTTP::Delete)]

    attr_accessor user_agent: String

    def initialize: (?user_agent: String) -> void
    def build: (http_method: Symbol, uri: URI::Generic, ?params: Hash[Symbol | String, untyped], ?body: request_body?, ?content_type: String?, ?headers: Hash[String, String], ?authenticator: Authenticator) -> Net::HTTPRequest

    private

    def create_request: (http_method: Symbol, uri: URI::Generic, params: Hash[Symbol | String, untyped]) -> Net::HTTPRequest
    def add_query_params: (URI::Generic uri, Hash[Symbol | String, untyped] params) -> URI::Generic
    def add_headers: (request: Net::HTTPRequest, headers: Hash[String, String]) -> void
    def add_body: (request: Net::HTTPRequest, body: request_body?, content_type: String?) -> void
    def add_authentication: (request: Net::HTTPRequest, authenticator: Authenticator) -> void
  end

  class RedirectHandler
    DEFAULT_MAX_REDIRECTS: Integer
    METHOD_PRESERVING_CODES: Array[Integer]

    attr_accessor max_redirects: Integer
    attr_reader connection: Connection
    attr_reader request_builder: RequestBuilder

    def initialize: (?connection: Connection, ?request_builder: RequestBuilder, ?max_redirects: Integer) -> void
    def handle: (response: Net::HTTPResponse, request: Net::HTTPRequest, ?authenticator: Authenticator, ?redirect_count: Integer) -> Net::HTTPResponse

    private

    def build_new_uri: (Net::HTTPResponse response, Net::HTTPRequest request) -> URI::Generic
    def build_request: (Net::HTTPRequest request, URI::Generic uri, Integer response_code, Authenticator authenticator) -> Net::HTTPRequest
  end

  class ResponseParser
    ERROR_MAP: Hash[Integer, singleton(HTTPError)]

    def parse: (response: Net::HTTPResponse) -> String

    private

    def error: (Net::HTTPResponse response) -> HTTPError
    def error_class: (Net::HTTPResponse response) -> singleton(HTTPError)
  end

end
