# Widen stdlib signatures to match runtime behavior used by Gems
module Net
  class HTTP
    def self.new: (String address, ?Integer? port, ?String | :ENV | nil p_addr, ?Integer? p_port, ?String? p_user, ?String? p_pass, ?untyped? p_no_proxy, ?bool? p_use_ssl) -> Net::HTTP

    def set_debug_output: (IO | Gems::RedactedOutput | nil output) -> void | ...
  end

  module HTTPHeader
    def set_form: (Array[[String | Symbol, untyped] | [String, untyped, Hash[Symbol, untyped]]] params, ?String enctype, ?Hash[untyped, untyped] formopt) -> void | ...
  end
end
