name: tests
# A tag is checked by push_gem.yml, which calls this workflow before it pushes the gem
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_call:
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "4.0", "head", "jruby"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake spec
